on:
  push:
    branches:
      - master



jobs:
  bulid:
    runs-on: ubuntu-latest

    steps:
      - name: 'print all folder before'
        run: ls

      - uses: actions/checkout@v3

      - name: 'login to doockerhup'
        run: docker login --username 0sama2001 --password 0$AM@200! dckr_pat_CCK_ZQxZQyhdfbAkW-uK-f6a9d8