on:
  push:
    branches:
      - master



jobs:
  bulid:
    runs-on: ubuntu-latest

    steps:
     

     - uses: actions/checkout@v3

     - name: 'login to doockerhup'
        run: docker login --username ${{secrets.SECRET_1}} --password 0$AM@200! ${{DOCKER_TOKEN}} 